### PR TITLE
how to test sync + async

### PR DESCRIPTION
**Pull request by threepointone**
a response to https://github.com/facebook/react/issues/15416

### CODE REVIEW

**Review by dirv — APPROVED** [review]

**Comment by dirv** [comment]
@threepointone do you know if there are plans to release async act as a 16.8.7 or will I need to wait for 16.9?

**Comment by threepointone** [comment]
16.9.

**Comment by dirv** [comment]
@threepointone Okay thanks for that. I'm about to have a book published which is dependent on this. (Mastering React TDD by Packt).

I'll include a note at the start explaining the situation to readers - that they should be using at least 16.9, even if it's still only in alpha!

By the way, would you like an acknowledgement in the book for helping me out with this?

**Comment by threepointone** [comment]
You don’t have to mention the alpha I think. We’re planning on releasing sometime next week hopefully. 

The acknowledgment isn’t needed, very kind of you :)

**Pull request merged**
